/*
  # Add price field to work assignments

  1. Changes
    - Add `price` column to `work_assignments` table
      - Type: numeric (to store monetary values)
      - Default: 0
      - Not null to ensure data integrity
    
  2. Purpose
    - Track revenue generated by each worker for each repair order
    - Enable financial reporting per worker and per assignment
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'work_assignments' AND column_name = 'price'
  ) THEN
    ALTER TABLE work_assignments ADD COLUMN price numeric DEFAULT 0 NOT NULL;
  END IF;
END $$;